import "./globals.css";
import localFont from "next/font/local";

// const votrag = localFont({
//   src: "/fonts/Votrag-Bold.ttf",
//   variable: "--font-votrag",
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>{children}</body>
    </html>
  );
}
